In [1]:
import pandas as pd
import geopandas as gpd

gdf_points = gpd.read_file ('data/points_events.geojson')
gdf_polygons = gpd.read_file ('data/polygons_districts.geojson')

In [3]:
import sys
import os

project_root = os.path.abspath(os.path.join('..')) 

if project_root not in sys.path:
    sys.path.append(project_root)

from src.sea import *

In [6]:
points = PointLayer(data=gdf_points)
polygons = PolygonLayer(data=gdf_polygons, name='name')

In [7]:
count_points_in_polygon (points, polygons)

name
Адмиралтейский район        1
Василеостровский район      1
Выборгский район           11
Калининский район           1
Кировский район             6
Колпинский район           10
Красногвардейский район     5
Красносельский район        7
Кронштадтский район         2
Курортный район            32
Московский район            8
Невский район               4
Петродворцовый район        9
Приморский район           12
Пушкинский район           23
Фрунзенский район           8
Центральный район           2
dtype: int64

In [8]:
counts = count_points_in_polygon (points, polygons)

In [9]:
calculate_density(polygons, counts)

,id,geometry,count,area,density
name,,,,,
Колпинский район,1,"MULTIPOLYGON (((3421694.425 8343157.656, 34178...",10.0,404.581205,0.024717
Пушкинский район,2,"MULTIPOLYGON (((3401477.637 8341502.336, 34014...",23.0,939.529258,0.024480
Московский район,3,"MULTIPOLYGON (((3366300.778 8358227.673, 33662...",8.0,291.570585,0.027438
Красносельский район,4,"MULTIPOLYGON (((3346826.847 8326256.525, 33477...",7.0,357.543028,0.019578
Петродворцовый район,5,"MULTIPOLYGON (((3344568.03 8369407.021, 334458...",9.0,438.243563,0.020537
Невский район,6,"MULTIPOLYGON (((3395859.687 8385490.403, 33957...",4.0,244.632256,0.016351
Фрунзенский район,7,"MULTIPOLYGON (((3377223.769 8378626.703, 33772...",8.0,148.139134,0.054003
Адмиралтейский район,8,"MULTIPOLYGON (((3377442.401 8381002.774, 33774...",1.0,54.722455,0.018274
Василеостровский район,9,"MULTIPOLYGON (((3368799.923 8381369.759, 33687...",1.0,85.936627,0.011636
Выборгский район,10,"MULTIPOLYGON (((3354511.577 8410596.336, 33611...",11.0,458.960029,0.023967
Калининский район,11,"MULTIPOLYGON (((3379614.767 8388926.642, 33784...",1.0,160.186500,0.006243
Кировский район,12,"MULTIPOLYGON (((3370471.597 8377972.803, 33704...",6.0,182.076854,0.032953
Красногвардейский район,13,"MULTIPOLYGON (((3384884.231 8390602.424, 33847...",5.0,223.825892,0.022339
Центральный район,14,"MULTIPOLYGON (((3377245.198 8382091.436, 33772...",2.0,70.289102,0.028454
Петроградский район,15,"MULTIPOLYGON (((3364532.513 8394621.019, 33641...",0.0,78.151666,0.000000
Кронштадтский район,16,"MULTIPOLYGON (((3316596.203 8405864.702, 33166...",2.0,80.027436,0.024991
Курортный район,17,"MULTIPOLYGON (((3305818.706 8452453.399, 33056...",32.0,1102.725578,0.029019
Приморский район,18,"MULTIPOLYGON (((3375402.215 8394945.676, 33752...",12.0,440.978559,0.027212

In [10]:
density_gdf = calculate_density(polygons, counts)

In [12]:
top_district (polygons, counts)

,id,geometry,count
name,,,
Курортный район,17,"MULTIPOLYGON (((3305818.706 8452453.399, 33056...",32.0
Пушкинский район,2,"MULTIPOLYGON (((3401477.637 8341502.336, 34014...",23.0
Приморский район,18,"MULTIPOLYGON (((3375402.215 8394945.676, 33752...",12.0
Выборгский район,10,"MULTIPOLYGON (((3354511.577 8410596.336, 33611...",11.0
Колпинский район,1,"MULTIPOLYGON (((3421694.425 8343157.656, 34178...",10.0
Петродворцовый район,5,"MULTIPOLYGON (((3344568.03 8369407.021, 334458...",9.0
Фрунзенский район,7,"MULTIPOLYGON (((3377223.769 8378626.703, 33772...",8.0
Московский район,3,"MULTIPOLYGON (((3366300.778 8358227.673, 33662...",8.0
Красносельский район,4,"MULTIPOLYGON (((3346826.847 8326256.525, 33477...",7.0
Кировский район,12,"MULTIPOLYGON (((3370471.597 8377972.803, 33704...",6.0
Красногвардейский район,13,"MULTIPOLYGON (((3384884.231 8390602.424, 33847...",5.0
Невский район,6,"MULTIPOLYGON (((3395859.687 8385490.403, 33957...",4.0
Кронштадтский район,16,"MULTIPOLYGON (((3316596.203 8405864.702, 33166...",2.0
Центральный район,14,"MULTIPOLYGON (((3377245.198 8382091.436, 33772...",2.0
Василеостровский район,9,"MULTIPOLYGON (((3368799.923 8381369.759, 33687...",1.0
Адмиралтейский район,8,"MULTIPOLYGON (((3377442.401 8381002.774, 33774...",1.0
Калининский район,11,"MULTIPOLYGON (((3379614.767 8388926.642, 33784...",1.0
Петроградский район,15,"MULTIPOLYGON (((3364532.513 8394621.019, 33641...",0.0